include Makefile.compilation

test_array:
	cd code; make test_array
	cd rapport; make all

test_list:
	cd code; make test_list
	cd rapport; make all

clean:
	cd code; make clean
	cd rapport; make clean