include ../Makefile.compilation

all: $(RAPPORTSOURCE).tex
	$(LATEX) $(RAPPORTSOURCE).tex
	$(LATEX) $(RAPPORTSOURCE).tex
	$(LATEX) $(RAPPORTSOURCE).tex

clean:
	rm -f *.aux *.log *.fls *.fdb_latexmk *.syntec.gz